services:
  causal-testing-framework:
    build:
      context: ../
      dockerfile: dafni/Dockerfile
    env_file:
      - .env
    volumes:
      - ./data/inputs:/data/inputs:ro
      - ./data/outputs:/data/outputs