repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        files: ^causal_testing/
      - id: end-of-file-fixer
        files: ^causal_testing/
      - id: check-added-large-files
        files: ^causal_testing/
      - id: check-merge-conflict
        files: ^causal_testing/
      - id: debug-statements
        files: ^causal_testing/
      - id: mixed-line-ending
        files: ^causal_testing/

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        args: ['--line-length=120', '--target-version=py310']
        files: ^causal_testing/

  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ['--profile', 'black', '--line-length', '120']
        files: ^causal_testing/

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ['--max-line-length=120', '--max-positional-arguments=12', '--disable=W1401']
        files: ^causal_testing/